sudo: required
services:
  - docker

before_install: 
  - docker build -t jcdsta/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true jcdsta/docker-react npm run test -- --coverage